### ISSUE TITLE
k8s ingress로 apigw 서비스 매핑

### ISSUE THREAD

**Issue by Ashon** [k8s-study/kong#2]
현재 NodePort로 minikube에서 외부로 서비스 하고 있는데 ingress를 이용해서 서비스를 노출해야 한다.

**Comment by asbubam** [comment]
뜬금없지만, 애션님 이슈를 메일로 받으니까 기분이 좋네요. :)

**Comment by Ashon** [comment]
옷... ㅋㅋ 저도 댓글 달아주시니 기분이 좋네요!

**Comment by raccoonyy** [comment]
기분 좋으시라고 댓글 하나 더...

**Comment by outsideris** [comment]
~맥락을 자세히 설명해 주세...~

**Comment by Ashon** [comment]
컥...

**Comment by tedpark** [comment]
kube yaml 에서 진도가 안나갑니다.. 언제 도움좀.. 또르륵..

**Comment by Ashon** [comment]
앗! 저도 잘 모르지만.. 도와드리겠습니다!

**Comment by Ashon** [comment]
closed by https://github.com/k8s-study/kong/commit/5e1a6c7ef773b6723c20703e6baf5063deb538ab
