### ISSUE TITLE
namespace로 프로젝트를 구분하면 좋을 것 같다.

### ISSUE THREAD

**Issue by Ashon** [k8s-study/kong#5]
kubectl로 서비스들 보면 오만게 다 나올거같은데, namespace로 분리해서 볼 수 있다면 좋을 것 같다.

``` sh
$ kubectl get all --namespace=apigw
```

**Comment by asbubam** [comment]
```
$ kubectl get all -n apigw
```
도 됩니다!

**Comment by Ashon** [comment]
@asbubam 오!! 감사합니다!

**Comment by Ashon** [comment]
closed by https://github.com/k8s-study/kong/commit/1c26f3a00a7144afa67af29b3837b4bd1b1e3eb1
